### ISSUE TITLE
Label not found: mris_label2annot

### ISSUE THREAD

**Issue by butellyn** [LCBC-UiO/ggsegExtra#11]
I am working on creating a ggseg atlas for MICCAI 2012/OASIS label set, but I am getting stuck on the mris_label2annot step. It cannot find my labels ("-l NOT_FOUND"). The files definitely exist, and they look like freesurfer's label files to me. Do you know what isn't being found? Thank you!

`OUTDIR=<directory on my computer>
INDIR=<directory on my computer>
SCRDIR=<directory on my computer>

# Subset parcellation to only include cortical ROIs
fslmaths ${INDIR}/mniMICCAI_LabelsWithWM.nii.gz -thr 100 -uthr 207 ${INDIR}/mniMICCAI_LabelsCortical.nii.gz

# Project volume to surface
mri_vol2surf --sd ${SUBJECTS_DIR} --src ${INDIR}/mniMICCAI_LabelsCortical.nii.gz --mni152reg --out ${OUTDIR}/output/miccai_2012_surf_rh.mgh --hemi rh --projfrac 0.5

mri_vol2surf --sd ${SUBJECTS_DIR} --src ${INDIR}/mniMICCAI_LabelsCortical.nii.gz --mni152reg --out ${OUTDIR}/output/miccai_2012_surf_lh.mgh --hemi lh --projfrac 0.5

# Create a color table (in R)
df <- read.csv("/Users/butellyn/Documents/hiLo/data/hilo_images/jlf_lookup/jlf_lookup.csv")
df <- df[df$ROI_INDEX %in% 100:207,]
df$R <- sample.int(256, 108)
df$G <- sample.int(256, 108)
df$B <- sample.int(256, 108)
df$A <- 0

write.table(df, "miccaiCtab.txt", row.names=FALSE, col.names=FALSE)

# Create a series of individual label files
mkdir ${OUTDIR}/Labels
nums=`seq 100 207`
for i in $nums ; do
	mri_vol2label --c ${OUTDIR}/output/miccai_2012_surf_rh.mgh --id ${i} --surf fsaverage rh --l ${OUTDIR}/Labels/rh_MIC_${i}.label
	mri_vol2label --c ${OUTDIR}/output/miccai_2012_surf_lh.mgh --id ${i} --surf fsaverage lh --l ${OUTDIR}/Labels/lh_MIC_${i}.label ;
done

# Create annotation files
surfids_L=`ls ${OUTDIR}/Labels/lh* | cut -d "_" -f 4 | cut -d "." -f 1`
LABS_L=""
for thisid in ${surfids_L}; do
  LABS_L=${LABS_L}"--l ${OUTDIR}/Labels/lh_MIC_${thisid}.label ";
done

surfids_R=`ls ${OUTDIR}/Labels/rh* | cut -d "_" -f 4 | cut -d "." -f 1`
LABS_R=""
for thisid in ${surfids_R}; do
  LABS_R=${LABS_R}"--l ${OUTDIR}/Labels/rh_MIC_${thisid}.label ";
done

# January 10, 2020: STUCK HERE
sudo mris_label2annot --sd ${SUBJECTS_DIR} --s fsaverage --ctab ${OUTDIR}/output/miccaiCtab.txt ${LABS_L} --h lh --a mic

sudo mris_label2annot --sd ${SUBJECTS_DIR} --s fsaverage --ctab ${OUTDIR}/output/miccaiCtab.txt ${LABS_R} --h rh --a mic`

**Comment by butellyn** [comment]
I tried re-indexing to start at 0, and that seemed to help, but it definitely created a new problem. Now many of the vertices (potentially all of them...) map to multiple labels.

**Comment by Athanasiamo** [comment]
Did you resolve this before opening the other ticket?

**Comment by butellyn** [comment]
This was not resolved, unfortunately. All of my labels are off in freesurfer, but it didn't end up mattering because these labels are not ultimately utilized by ggseg. Does that make sense?

**Comment by Athanasiamo** [comment]
it does make sense. We abandonned this part of the pipeline in the new atlas creating function, though I am currently working on making something that could do something like this, but it's still going to need some work. 

I'm going to close this issue as it's not technically needed anymore. If you end up needing this again, re-open it.
