### ISSUE TITLE
Unknown file in atlas creation instructions

### ISSUE THREAD

**Issue by butellyn** [LCBC-UiO/ggsegExtra#13]
What file is this: `fsaverage_lh_10.label.gii`? It is not generated in the atlas creation instructions script (https://github.com/LCBC-UiO/ggsegExtra/wiki/Contributing%3A-polygon-atlases-new), and it doesn't seem to exist within freesurfer itself. A little more annotation in Step 7 would be really helpful. Thanks!

**Comment by butellyn** [comment]
smooth_labels.sh fails here: `sed -n '0~2!p' ${TD}/a > ${TD}/names`. It gives this error: `sed: 1: "0~2!p": invalid command code ~`. What are you trying to accomplish here? Maybe I can do it another way.

**Comment by butellyn** [comment]
Similarly, what is `inflated_lh.surf.gii`?

**Comment by Athanasiamo** [comment]
Hi! Sorry for being so late in replying.

**Comment by richardbeare** [comment]
This command is deleting every second line from the label file out. I can't remember why this was necessary.

Are you running on a mac? It is possible the error is due to different sed versions. If you are on a mac and have homebrew installed then you could change to gsed to see if it fixes the problem.

**Comment by butellyn** [comment]
@richardbeare Interesting, didn't know sed differed across operating systems. I am using a mac. I ended up doing this: 
`i=1
while read p; do
  if [ $((${i}%2)) -eq 1 ] ; then echo ${p} >> ${TD}/names; fi ; i=$((i + 1)) ;
done < ${TD}/a`

@Athanasiamo So should these two lines be
`mris_convert --annot ../label/rh.ho.annot ../surf/rh.inflated ./inflated_rh.surf.gii
mris_convert --annot ../label/lh.ho.annot ../surf/lh.inflated ./inflated_lh.surf.gii`

**Comment by richardbeare** [comment]
linux has gnu sed, mac bsd sed. You can get gsed via homebrew on the mac. The command may have some subtleties to it (leaving a header line), just check what the input file looks like. awk is probably another alternative too.

There should be two mris_convert commands - on separate lines.

FYI - the reason for all the trouble was that projecting the HO atlas to a surface lead to a really ugly looking map, with labels crossing sulcal folds and leaving holes. The only way I could think of auto-correcting it was to do morphology and smoothing operations on the surface, and connectome workbench is the best tools for that kind of stuff that I am aware of. It works best on gii files. Hence the conversion.

**Comment by Athanasiamo** [comment]
We've made a pipeline for creating atlases where this seems to not be an issue. Hope it helps:

https://lcbc-uio.github.io/ggsegExtra/articles/customatlas.html
