### ISSUE TITLE
not able to load ggsegExtra

### ISSUE THREAD

**Issue by mvlombardo** [LCBC-UiO/ggsegExtra#18]
Hi, I'm having a problem using ggsegExtra. I have tried this below, but get a message about an .rdb file being corrupt. What should I do?

`library(ggseg)`

`library(ggsegExtra)`

`Error in FUN(X[[i]], ...) : 
  lazy-load database '/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ggseg/data/Rdata.rdb' is corrupt
In addition: Warning messages:
1: In FUN(X[[i]], ...) : restarting interrupted promise evaluation
2: In FUN(X[[i]], ...) : internal error -3 in R_decompress1`

**Comment by mvlombardo** [comment]
I think I might have solved the problem.

I closed RStudio and tried again, but this time I first did:

`library(tidyverse)`

and then 

`library(ggseg)`
`library(ggsegExtra)`

And for some reason, its now working...

**Comment by Athanasiamo** [comment]
great you got it working! :) i'll look into bugs that might occur with loading packages in specific orders. but i have hd this issue before when updating ggseg packages while they are loaded, which throws this error. but restarting R thankfully fixes it.
