### ISSUE TITLE
Exclude NA from legend

### ISSUE THREAD

**Issue by butellyn** [LCBC-UiO/ggsegExtra#24]
Is it possible to exclude NA from the legend here `ggseg(atlas="aseg", mapping=aes(fill=region))`. If so, how would you do it? I tried adding `na.rm=TRUE`, but that didn't do anything.

**Comment by Athanasiamo** [comment]
It is not arbitrary to remove such a thing, so that would not the it I'm afraid.

The best you can do it perhaps try to adapt [this solution](https://stackoverflow.com/questions/21801950/remove-legend-entries-for-some-factors-levels) on stackoverflow to what you are attempting to do.

**Comment by butellyn** [comment]
Thank you! Got it working.

**Comment by Athanasiamo** [comment]
awesome! Would you mind posting your solution here? I can imagine it is not the last time someone would want to do this :)

**Comment by butellyn** [comment]
Yup! 
`aseg <- aseg[!is.na(aseg$area),]

ggseg(atlas="aseg", mapping=aes(fill=area)) + scale_fill_manual(values=c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7", "#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7", "#CC6666", "#9999CC"), breaks=unique(aseg$area), drop=FALSE)`

**Comment by butellyn** [comment]
To have the regions that are NA still display, you'd have to create two versions of the aseg atlas, and pass the one with the NAs excluded as the first argument (before atlas) to ggseg.
