### ISSUE TITLE
Version of ggseg where ".subid" and "region" columns are not required

### ISSUE THREAD

**Issue by butellyn** [LCBC-UiO/ggsegExtra#25]
I am remaking an old figure with my custom atlas using the MICCAI label set, but in the meantime I got a new computer and had to reinstall ggseg. Ggseg seems to have changed versions since, and now I need ".subid" and "region" columns for my atlas to be a valid ggseg atlas. What version of the package did not require these? I failed to record what version of the package I was using before.

**Comment by Athanasiamo** [comment]
Hi!

Sorry for the inconvenience! Very likely you can get away by doing two things:
1. rename `area` to `region` (we did this to avoid naming conflict with areal-calculation stats)  
2. add `.subid = 1` to all polygons. This was an improvement to allow polygons that might have holes in them, if none of your regions have holes, that column need only be a single value. 

Something like this should work:
```r
library(ggseg)
library(tidyverse)

miccai <- miccai %>%
   rename(region = area) %>%
   mutate(ggseg = map(ggseg, ~ mutate(.x, .subid = 1))
```

I'd give that a go before reverting

**Comment by butellyn** [comment]
Ah! I still have a hole problem (more like a gap problem). How can I used .subid to fill holes?

**Comment by Athanasiamo** [comment]
no, it wont fill the gaps I'm afraid, it will just enable you to have holes in your polygons of they are supposed to be there.
