### ISSUE TITLE
make_palette_ggseg hard-coded to "LCBC" surface

### ISSUE THREAD

**Issue by monicathieu** [LCBC-UiO/ggsegExtra#27]
Hi again,

I have recently been using this package to make a custom-ish atlas for the Schaefer 2018 parcellations, as for some reason the region names in the parcellation order file I have don't line up with the names in the `ggsegSchaefer` package. I figured I might want to make a version of the atlas for myself to make sure I'm plotting the right values onto the right brain regions!

After installing freesurfer and its R wrapper package, and messing with a couple things, I successfully used `make_aparc_2_3datlas()` to convert the relevant freesurfer annotation files to 3D atlases. Next, I tried to run `make_ggseg3d_2_ggseg()` to snapshot the 3D atlases down to 2d. All of these atlases are using `surf == "inflated"`. I got the following error:

```
Error: Can't subset columns that don't exist.
x Column `region` doesn't exist.
```

Based on the fact that no other progress messages had appeared, I think the error may be happening very early, probably when `make_palette_ggseg()` is called. [That function](https://github.com/LCBC-UiO/ggsegExtra/blob/04b8a25e0ac945619eeff38eebf695b4a204e2e2/R/create-ggseg-atlas.R#L251) appears to be hard-coded to filter for `surf == "LCBC"`, thus probably yielding a 0-length dataframe for any other surface type and throwing an error in the `select()` call 2 lines down.

I think this should be a quick fix to feed `surf` in as an argument to `make_palette_ggseg()` to patch this up. Thank you again for all your work!

**Comment by Athanasiamo** [comment]
HI!

Right, indeed that would give an error. But since you've done such a thorough job finding where the issue arises, the problem should be fixed in the release I just made. 

OS checks are still running, but you can try the new version out if you like :)

**Comment by monicathieu** [comment]
Thank you so much for patching this so quickly! It looks like it's running smoothly now :)

Mostly unrelated to this issue, but perhaps a useful note to include for anyone who might make the mistake I just made: it looks like `make_ggseg3d_2_ggseg()` expects a bilateral atlas. The way I'd set up `make_aparc_2_3datlas` to run first, I had a list of atlases, with a separate ggseg3d-atlas dataframe for every hemisphere of every parcellation. When I went to run `make_ggseg3d_2_ggseg()`, steps 1-6 ran smoothly and then I got a funny error in step 7.

From debugging:
```r
> atlas_df_sf <- ggsegExtra:::adjust_coords_sf(atlas_df_sf)
Error in atlas[[4]] : subscript out of bounds
```

Upon poking in, I realized I was meant to feed in a whole bilateral atlas to `make_ggseg3d_2_ggseg()` and that it was erroring out because it was looking for 2 hemispheres' worth of views and only finding 1. I combined the appropriate left and right hemisphere atlas dataframes, re-ran the function, and it worked all the way through! Hope this helps somebody else in the future.

**Comment by Athanasiamo** [comment]
oh, this is actually a bug! Thanks, for letting us know. I'll make sure to tackle this at the next fix

**Comment by Athanasiamo** [comment]
I'll close this issue now, as I made a separate one based in your last comment.

**Comment by monicathieu** [comment]
got it! thanks for resolving both of these.
