### ISSUE TITLE
atlas with Allen brain namings?

### ISSUE THREAD

**Issue by AMChalkie** [LCBC-UiO/ggsegExtra#5]
Hi,

Great tool, thanks first and foremost. 

Was looking to use data from Allen brain structures, which doesn't map to any areas in the atlas. It would be useful to either have a "map from allen", or to have an allen brain map of these general regions.

https://mouse.brain-map.org/gene/show/35697

"midbrain"              "isocortex"             "medulla"               "striatum"              "cerebellum"            "thalamus"              "olfactory areas"       "cortical subplate"     "pons"                  "pallidum"              "hippocampal formation" "hypothalamus"

**Comment by Athanasiamo** [comment]
Hi!

We dont have any mouse brain projections, for that we recommend looking into https://github.com/jespermaag/gganatogram

If you mean having an atlas with equivalent regions on the human brain, we welcome contributions to this, though parcellations of subcortical structures are quite difficult to make and we do not have a proper pipeline in place for this, as brain slices where the regions you'd like to be on display have to be manually set and traced (currently).
