### ISSUE TITLE
Custom Atlas having annot and color table.

### ISSUE THREAD

**Issue by ldehoyos** [LCBC-UiO/ggsegExtra#8]
Hi,
Regarding the custom atlas creation, I have a question of what steps I need to do next. I already have an annot of a custom atlas (‘cus’) with a color table in fsaverage-space (which looks just fine). 
Having this, what steps need to be taken to obtain cus_atlas.Rda?

**Comment by butellyn** [comment]
Can you add the MICCAI 2012 atlas? 

Labeling protocol: http://neuromorphometrics.com/ParcellationProtocol_2010-04-05.PDF

In MNI 152 space:
[mniMICCAI_LabelsWithWM.nii.gz](https://github.com/LCBC-UiO/ggsegExtra/files/4036273/mniMICCAI_LabelsWithWM.nii.gz)

Index names:
`ROI_INDEX,ROI_NAME
1,Unlabeled
2,aals
3,ahls
4,3rd_Ventricle
5,calcarine
6,central
7,central_insular
8,cingulate
9,circular
10,collateral
11,4th_Ventricle
12,first_transverse
13,Heschls
14,inferior_frontal
15,5th_Ventricle
16,intraparietal
17,primary_inter
18,lateral_occipital
19,occ_temporal
20,olfactory
21,par_occipital
22,pals
23,R_Accumbens
24,phls
25,postcentral
26,precentral
27,subparietal
28,superior_frontal
29,superior_temporal
30,L_Accumbens
31,R_Amygdala
32,L_Amygdala
33,R_Amygdala
34,L_Amygdala
35,Brain_Stem
36,R_Caudate
37,L_Caudate
38,R_Cerebellum
39,L_Cerebellum
40,R_Cerebellum
41,L_Cerebellum
42,R_Cerebral
43,L_Cerebral
44,R_Cerebral
45,L_Cerebral
46,CSF
47,R_Hippocampus
48,L_Hippocampus
49,R_Inf
50,L_Inf
51,R_Lateral
52,L_Lateral
53,R_Lesion
54,L_Lesion
55,R_Pallidum
56,L_Pallidum
57,R_Putamen
58,L_Putamen
59,R_Thal
60,L_Thal
61,R_Ventral
62,L_Ventral
63,R_vessel
64,L_vessel
65,L_Insula
66,R_Insula
67,L_Operculum
68,R_Operculum
69,Optic_Chiasm
70,Basal_Forebrain
71,Cerebellar_Vermal
72,Cerebellar_Vermal
73,Cerebellar_Vermal
74,Vitamin_E
75,L_Basal_Forebrain
76,R_Basal_Forebrain
80,frontomarginal
81,inferior_rostral
82,inferior_temporal
83,lateral_orbital
84,superior_rostral
85,lateral
86,anterior_occipital
87,lhos
88,mhos
89,superior_vermal_sulcus
90,central_vermal_sulcus
91,inferior_vermal_sulcus
92,lateral_vermal_sulcus
93,thos
97,RED
98,YELLOW
99,CYAN
100,R_ACgG
101,L_ACgG
102,R_AIns
103,L_AIns
104,R_AOrG
105,L_AOrG
106,R_AnG
107,L_AnG
108,R_Calc
109,L_Calc
110,R_CgG
111,L_CgG
112,R_CO
113,L_CO
114,R_Cun
115,L_Cun
116,R_Ent
117,L_Ent
118,R_FO
119,L_FO
120,R_FRP
121,L_FRP
122,R_FuG
123,L_FuG
124,R_GRe
125,L_GRe
126,R_IFG
127,L_IFG
128,R_IOG
129,L_IOG
130,R_IOrG
131,L_IOrG
132,R_ITG
133,L_ITG
134,R_LiG
135,L_LiG
136,R_LOrG
137,L_LOrG
138,R_MCgG
139,L_MCgG
140,R_MFC
141,L_MFC
142,R_MFG
143,L_MFG
144,R_MOG
145,L_MOG
146,R_MOrG
147,L_MOrG
148,R_MPoG
149,L_MPoG
150,R_MPrG
151,L_MPrG
152,R_MSFG
153,L_MSFG
154,R_MTG
155,L_MTG
156,R_OCP
157,L_OCP
158,R_OFC
159,L_OFC
160,R_OFuG
161,L_OFuG
162,R_OpIFG
163,L_OpIFG
164,R_OrIFG
165,L_OrIFG
166,R_PCgG
167,L_PCgG
168,R_PCu
169,L_PCu
170,R_PHG
171,L_PHG
172,R_Pins
173,L_Pins
174,R_PO
175,L_PO
176,R_PoG
177,L_PoG
178,R_POrG
179,L_POrG
180,R_PP
181,L_PP
182,R_PrG
183,L_PrG
184,R_PT
185,L_PT
186,R_SCA
187,L_SCA
188,R_SCLC
189,L_SCLC
190,R_SFG
191,L_SFG
192,R_SMC
193,L_SMC
194,R_SMG
195,L_SMG
196,R_SOG
197,L_SOG
198,R_SPL
199,L_SPL
200,R_STG
201,L_STG
202,R_TMP
203,L_TMP
204,R_TrIFG
205,L_TrIFG
206,R_TTG
207,L_TTG`
